### ISSUE TITLE
Add "loading..." to the CWRC entity preview in the entity lookups

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#100]
@ajmacdonald , I think this is necessary due to the delayed loading caused by the Entity Aggregation Pages

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-PublicEntityDialogs/commit/e7590242341d9a02b3a1260b3bfba24713ceb83b

**Comment by ilovan** [comment]
confirmed

**Comment by ilovan** [comment]
work complete and deployed
