### ISSUE TITLE
Dev CWRC-Writer down (502 Bad Gateway when clicking on "Authenticate with GitHub")

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#101]

**Comment by jchartrand** [comment]
That took me longer to figure out than it should have (I misread the error messages and followed too many false leads), but in the end it was just that the gitserver on dairies had gone down for some reason.  It's like the advice that if your computer isn't working, the first thing to check is that it is plugged in.  Anyhow, now fixed.
