### ISSUE TITLE
Update or remove stale tester documentation

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#103]
Especially the link to the old testing site on the first page: https://sites.google.com/site/cwrcwriterhelp/home

**Comment by SusanBrown** [comment]
Not that I am aware of, but who knows?


On Jun 21, 2018, at 9:25 AM, Mihaela Ilovan <notifications@github.com<mailto:notifications@github.com>> wrote:


This is so old I didn't even know of its existence!!!

https://sites.google.com/site/cwrcwriterhelp/

Are there any other similar fossils around?

**Comment by ilovan** [comment]
I can't even sign in to this one - @SusanBrown  - so if you can - can you please put it to rest? if not - I have a strong feeling that people will not be able to find it very easily.

**Comment by ilovan** [comment]
closing it anyway , since it is very inconsequential
