### ISSUE TITLE
Initial layout is incorrect

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/CWRC-WriterBase#106]
There is inconsistency between the panel sizes and the resize bar when cwrc writer loads initially.

## Expected Behaviour
The sizing should be consistent

## Current Behaviour
It's not consistent

## Steps to Reproduce (for bugs)
Load the CWRC-Writer

![layout.png](https://images.zenhubusercontent.com/5a6124b24b5806bc2bc3566f/2b10573e-12d1-425e-9d1d-7355e9bed44a)

## Your Environment
* URL: https://dev-cwrc-writer.cwrc.ca/

* Browser Name: Chrome

* Operating System: Windows

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/1c10ab7754a93087d56c20dad2c90da0c8126206

**Comment by ilovan** [comment]
work complete and deployed
