### ISSUE TITLE
Check for root element when loading a document and display a warning sign if not a supported schema

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#111]
## Expected Behaviour

When loading a document, check for root element. If different from:
BIOGRAPHY, CWRC, EVENT, TEI, or WRITING, display warning message:

> The document you are loading is not fully supported by CWRC-Writer. You may not be able to use the ribbon to tag named entities. To proceed, click "OK". To load a different document, click "Re-load".

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/18e7c045e9964d0a1664f69d3ff2e5893cd85dc8
https://github.com/cwrc/CWRC-WriterBase/commit/aac43b2223da9dde52caa164daf11a901c1725b9
