### ISSUE TITLE
Editor context menu doesn't take scroll into account

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/CWRC-WriterBase#115]
## Expected Behaviour

The context menu should appear at the mouse cursor position.

## Current Behaviour

If the editor is scrolled, the context menu will be offset by the scroll amount.

## Your Environment
* URL:
https://dev-cwrc-writer.cwrc.ca
* Browser Name:
Chrome
* Operating System:
Windows

**Comment by ajmacdonald** [comment]
This is fixed on the gitwriter version but more work is necessary for the integrated version.

**Comment by ajmacdonald** [comment]
1ece8da3262aa6b95886df036cd73a2276e4a2fc

**Comment by ilovan** [comment]
confirmed
