### ISSUE TITLE
In TEI-based schemas, when generating the RDF, use @ana instead of @annotationID.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#116]
Note that @ana can have multiple values, so if there is already an @ana attribute on the entity tag, add the entity ID as an additional value. 

For example, 

``` <orgName ana="poetic">....</orgName>```
would become
``` <orgName ana="poetic ent_203">....</orgName>```

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/14264bafc94a4bbd7f312c81ad7de0f7eb437591

**Comment by ilovan** [comment]
Solution found too resource-intensive; https://github.com/cwrc/CWRC-WriterBase/issues/119 proposed instead.
