### ISSUE TITLE
Entity lookup pop-up (all entity lookups): make all searches dynamic

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#12]
This would remove the need for a "Search again" button.
How difficult to implement? Also, would it slow down the search?

**Comment by jchartrand** [comment]
I think you mean use look-ahead for the search field.  If so:

1.  yes, that would likely slow down the search.  We’d have to test to know if the slowness would be acceptable.  

2. The code would be more complicated.  I had look-ahead for the single VIAF search, but that was look-ahead on a single source.  Looking ahead for multiple sources would be more involved.   

3.  Each entity source has a different search interface - some support lookahead, some don’t.  DBpeida has it:  http://lookup.dbpedia.org/api/search/PrefixSearch?QueryClass=&MaxHits=5&QueryString=berl <http://lookup.dbpedia.org/api/search/PrefixSearch?QueryClass=&MaxHits=5&QueryString=berl>  but wikidata doesn’t.  This could make for confusing results.

4. The lookahead results are different from the full search results.  We show full search results.  If we wanted to use just the lookahead we’d have less meaningful results, or we could try to combine the lookahead and full results, but I can’t easily see how the would work with multiple sources.

In any case, however you’d like it changed, just sketch it out and we can discuss.

**Comment by ilovan** [comment]
How about if instead of having all the entity lookups expanded from the get go, we would have all of them collapsed and have the look-ahead provide just dynamic record counts on each list label


E.g.
Search: "John"
VIAF (10)
DBpedia (6)
Getty (5)

Search: "John S"
VIAF (7)
DBpedia (3)
Getty (0)

Users could expand the lists one at a time. 

Would this speedup things and/or simplify code. 

Just speaking hypothetically at this point - exploring different return options.

**Comment by jchartrand** [comment]
That does away with the primary reason for a look-ahead (auto-*suggest*) which suggests full terms based on partial input, e.g., you type ‘Joh’ and it suggests John, or Jonathon (if it uses fuzzy matching), etc.

Instead, I think what you are now suggesting is a way to declutter the initial view.  And, collapsing all the panels initially might make the interface less cluttered, but I don’t know how much is gained from that?  Won’t people almost always want to see the full results?

Further, the entity sources seem to return such weird results (e.g., VIAF) that just showing numbers of results might not really indicate anything meaningful at all.

As far as speed goes, the results are returned quickly already.  If it is if we went to lookahead/autosuggest then they could become slow.

**Comment by ilovan** [comment]
It's not ideal, I acknowledge but on the other hand I still think that having to "Search again" is an extra step for the user that will not fly very well. 

I'll assign this to Susan as well, I'm sure she would want to weigh in and we can move forward from there.

**Comment by jchartrand** [comment]
Note that you can simply hit ‘return’ after changing the text in the input box, which is what I’d expect most people would intuitively do.

**Comment by SusanBrown** [comment]
Let's not do look-aheads or advance counts but instead expand one source only.
Having people able to modify what's in the search box and hit return to rerun the search is fine. We may need to flag the ability to modify it--Mihaela can you make a note to test for this?--but let's not do anything about that now.

It would be ideal to make the search box that is by default opened configurable for the project being written to, i.e. CWRC, Orlando or (coming soon) REED. This came up at the recent demo.

**Comment by ilovan** [comment]
@SusanBrown,

I addressed your comment partially in https://github.com/cwrc/viaf-entity-lookup/issues/1#issuecomment-345348353.
Please review proposed mockup.
