### ISSUE TITLE
Entities tagged inside a note or citation don't get created as rdf annotations.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#122]
## Expected Behaviour
If an entity is tagged inside a note or citation mini-CWRC-Writer, when the main CWRC-Writer is in xml & rdf mode, an rdf annotation should be created for the entity inside the note.

## Current Behaviour

Entities don't get created: see https://github.com/ilovan/Git-Writer-tests/blob/master/newRDF-Dec_10-take3 

## Steps to Reproduce 

1. Go to dev CWRC-Writer and load https://github.com/ilovan/Git-Writer-tests/blob/master/newRDF-Dec_10-take3 or another TEI document
2. Select text and click on "tag note" on the ribbon
3. in the mini  CWRC-Writer loaded, select the note tag in the structure panel to italicized
4. Type a sentence, select a word and tag it as an entity
5. Save the content of the note and return to the main editor.
Result: 
* tags added: both the note and the entity it contains
* rdf added: just for the note.

## Console log

![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/db3ad2cf-9773-4363-85e3-89beab887e95)

**Comment by ilovan** [comment]
also, @ajmacdonald , any idea why it asks for the Epidoc schema if the current doc is a CWRC TEI lite?
Look

**Comment by ajmacdonald** [comment]
By default it tries to load all the schemas and determine what their root/start elements are, in case we need that info as fallback for document-schema matching. The Epidoc schema error shows up in the console because it always fails to load that schema.

**Comment by ilovan** [comment]
confirmed
