### ISSUE TITLE
keyword not visible on hover over

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#131]
## Expected Behaviour

keyword behaviour should be similar to the behaviour of links entities:

* if the keyword has an @ana attribute value, the mouseover should display the text of the keyword, linking to the URI specified in the ana attribute.
* if the keyword has no ana attribute value specified, the mouseover should only display the text of the keyword

## Current Behaviour
text/value of the keyword, once set, is only visible only if the user goes "Edit Entity"

**Comment by ilovan** [comment]
Adding slack conversation for future reference:

<img width="798" alt="screen shot 2019-02-07 at 11 47 51 am" src="https://user-images.githubusercontent.com/6600070/52435121-3c037580-2ace-11e9-840f-2f0f5aaa7f27.png">

**Comment by ajmacdonald** [comment]
c8837b4505fcce767117f9026ee5e4fead9ef30a

**Comment by ajmacdonald** [comment]
bb56d5aa3cba7e6f27e4a80f25703d62a262758d

**Comment by ilovan** [comment]
confirmed
