### ISSUE TITLE
Loading mask doesn't always disappear after hard reload

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/CWRC-WriterBase#140]

**Comment by ajmacdonald** [comment]
cwrcWrapper sometimes has 0 height which causes the resize method to return: https://github.com/cwrc/CWRC-WriterBase/blob/master/src/lib/jquery/jquery.layout_and_plugins.js#L4542-L4543

**Comment by lucaju** [comment]
Test in different browsers
