### ISSUE TITLE
Vetted NERVE entities do not get saved when the document is being saved

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#147]
## Expected Behaviour

The entities that I have vetted in a previous work session should be part of the markup next time when I open the file in GitWriter and be listed as entities in the entity panel. 

## Current Behaviour
Entities that I have accepted are not being saved.

## Steps to Reproduce (for bugs)

1. Open `ilovan/T.S.-Eliot---Old-Possum-s-Book-of-Practical-Cats-first-three-poems-`
2. run Nerve (either `recognition` or `recognition & linking`)
3. accept `Demeter` as is and link `Maidenhead` to Geonames entity and accept it
4. reject all other entities
5. hit `Done` on the NERVE panel
6. save document at `ilovan/T.S.-Eliot---Old-Possum-s-Book-of-Practical-Cats-first-three-poems-`
7. reload

## Your Environment
* URL: dev-cwrc-writer

* Browser Name:

Mac - Firefox

* Attachements:

See https://github.com/ilovan/T.S.-Eliot---Old-Possum-s-Book-of-Practical-Cats-first-three-poems-/commit/6ae52b412635784fbb6f79519c4d7396b633b781 for reference

**Comment by ajmacdonald** [comment]
Looks like this is caused by the current (temporary) URI generation: https://github.com/cwrc/CWRC-WriterBase/blob/master/src/js/annotationsManager.js#L330-L348

I imagine this will be reworked as part of the whole RDF redo but in the meantime I'll try to come up with a workaround.

**Comment by ilovan** [comment]
if this is a temporary fix - don't spend a lot of time on it (I imagine
we'll get so the rdf rework soon enough)

>

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/5234b463d6957563e71feeace6d397654d567d69

**Comment by ilovan** [comment]
Confirmed working

**Comment by ilovan** [comment]
still an issue with cwrc-writer.cwrc.ca and will be until the new rdf is in place, unless something else can be temporarily arranged, right @ajmacdonald ? One way or anotehr, this needs to be fixed before the conference.

**Comment by ajmacdonald** [comment]
The version on https://cwrc-writer.cwrc.ca/ includes the fix from April 2 and is working for me. If it's not working for you please let me know @ilovan

**Comment by ilovan** [comment]
confirmed
