### ISSUE TITLE
NERVE panel - in filtered view, re-classing an entity does not remove it from the current view

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#148]
## Expected Behaviour

Re-classed entity should be removed from the current filter view.

## Current Behaviour

If I have 3 person entities listed in the `people` filter and I edit one to re-class it as an organization, the entity still shows up in the `people` view, albeit visibly re-classed
![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/29d3728b-0252-42a1-a260-76bfe6dbaa32)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/ed80e8d4d8664f2f4679e0b24b5829de74a17055

**Comment by ilovan** [comment]
Confirmed

**Comment by ilovan** [comment]
confirmed in both production environments
