### ISSUE TITLE
Note and Citation mini CWRC-Writers not working.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#15]
![citation minicwrc-writer not working](https://user-images.githubusercontent.com/6600070/32967272-3cec2d6e-cb9a-11e7-8a3e-7ea27d3a62b4.PNG)
![note minicwrc-writer not working](https://user-images.githubusercontent.com/6600070/32967274-3d074586-cb9a-11e7-83ac-9b2cba70b691.PNG)

**Comment by jchartrand** [comment]
I think this should go to Andrew, unless there is something I am overlooking.

**Comment by ilovan** [comment]
OK. Reassigned.

**Comment by ajmacdonald** [comment]
@ilovan I moved this to Review/QA because it's now implemented/fixed on dev-cwrc-writer

**Comment by ilovan** [comment]
confirmed

**Comment by ilovan** [comment]
fix confirmed on dev-06 and Prod Git-Writer
