### ISSUE TITLE
Remove note tag in letter template

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#153]
There is a note tag that is prompting users when they open the template to create a new entity. It's the second entity in the image below. Unless I'm misunderstanding what's happening, I think it ought to be deleted from the template. @ilovan can you please do this?

![image.png](https://images.zenhubusercontent.com/5a60ec3a4b5806bc2bc34e2e/82f12435-c0f6-49cb-a6c7-813f5a31989d)

**Comment by ajmacdonald** [comment]
Instead of removing the note tag from the template, maybe the entity conversion process should be re-worked.

**Comment by ilovan** [comment]
I agree with @ajmacdonald 
I think the notes should be subject to automatic conversion upon ingestion only if they have the type attribute values corresponding to research note or scholar note in the current document schema. (For example, in the template, the tag "note" is used canonically in the TEI letter sample, but it is neither a research note, nor a scholar note. 

wdyt, @SusanBrown ?

**Comment by ilovan** [comment]
![image](https://user-images.githubusercontent.com/6600070/56226854-6d9a3f00-6031-11e9-919d-0c924f8840b6.png)

OK-ed by @SusanBrown

**Comment by ajmacdonald** [comment]
8cf2285be72c0561d79d9dada401396bda8bd583

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/17f11c3a5c834c2fff06f7a0b9079bac60ad019b
