### ISSUE TITLE
Converting tags to entities on ingestion bug?

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#155]
On the Git-Writer dev site, I opened the sample letter template. I was asked if I wanted to convert 1 entity and said yes (this was a note entity. See https://github.com/cwrc/CWRC-WriterBase/issues/153). I added 2 note tags (one with an embedded orgname and one with an embedded citation), a citation tag, and a corr tag (one which I didn't compled by adding a value). I then went into direct edit mode and searched on but did not modify the base markup. Upon exiting direct edit mode I was asked if I wanted to convert 7 tags to entities. That made me fear that I was creating new entities. 

There may be an easy explanation for this and if not it probably needs some more careful diagnosis to figure out what is happening and what should be done. It seems to me that either the message is wrong or duplicate entities are being created.

I've saved my document here (after much effort): https://github.com/SusanBrown/planet-susan/blob/master/notetest1

**Comment by ilovan** [comment]
Summary of discussion with @ajmacdonald :
This bug is related to general handling of the entity conversion and may be fixed already by yet-to-be-deployed changes to the code

**Comment by ilovan** [comment]
The issue is no longer relevant due to the changes in the entity scraping handling
