### ISSUE TITLE
Create splash page for Git-Writer

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#157]
Should provide:
- [x] brief description
- [x] quick start instructions or link thereto
- [x] link to documentation
- [x] credits
- [x] link to codebase
- [x] bug report / feature request link

**Comment by ilovan** [comment]
> Welcome to CWRC-Writer, the XML & RDF online editor developed by the Canadian Writing Research Collaboratory (cwrc.ca). 
> Git-Writer provides light-weight wysiwyg editing of XML documents and fully converts, upon request, xml named entities (persons, organization, places, titles) and document annotations (notes, citations, corrections, links) to xml rdf or Json-ld annotations fully compatible with the Web Annotation Data Model. 
> You can use CWRC-Writer to either lightly edit your XML document, to add linked open data capability to it to increase the interoperability of your document, or both. 
> Your documents are stored in GitHub, so you will need to login to your GitHub account in order to use CWRC-Writer. 
> To learn more about how to use CWRC-Writer, please go to cwrc-writer.cwrc.ca/documentation. We recommend that you start with the `video tutorial` and the `quick start guide`
> 
> CWRC-Writer is still under development, so if you run into an issue or there is a feature you would like to see added, please submit a ticket to https://github.com/cwrc/CWRC-WriterBase
> 
> If you are a developer interested in adopting/adapting the Writer in a different environment, please consult https://github.com/cwrc/tech_documentation/blob/master/Tools-reference.md#cwrc-writer. You can also contact us through a GitHub ticket on any of the CWRC-Writer code repositories.
> 
> Development team:
> 
> Andrew McDonald, 20? - present
> James Chartrand, 20? - 2018
> 
> Management, Q/A team:
> 
> Susan Brown, 20? - present
> Mihaela Ilovan, 2014 - present
> Megan Sellmer, 20? - 2016
> 

Still to do:

- [ ] redo the video
- [ ] move the GitWriter documentation to cwrc-writer.cwrc.ca/documentation
- [ ] translate to DITA a bunch of Git-Writer draft documentation.

**Comment by ilovan** [comment]
@SusanBrown , have a look, pls.

**Comment by SusanBrown** [comment]
I've revised it. I think this will do for now. @ilovan, can you use a current working link for the documentation and then update when it's moved, or can you move it right away? @ajmacdonald I based your start date on email records because you weren't working directly for CWRC at the time. If I'm wrong, please correct.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-git-dialogs/commit/b41a8db0f81b28d22b1e9a07c1f04cba74447881
