### ISSUE TITLE
Entity panel - "remove" outcome

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#159]
## Current Behaviour

For both scraped and unvetted entities, as well as for actual entities (created in CWRC-Writer or vetted from NERVE or the scraping process) - clicking on "remove" removes both the LOD annotation (for actual entities) as well as the XML tagging (for both actual and candidate entities in both NERVE and Entities pannel. 

###  Possible distinctions:

Remove NERVE candidates: 

- remove tagging; do not add LOD annotation

Remove scraping candidates: 

- do not  remove tagging (which was added by hand by a user) but do not add LOD annotation

Remove actual entities: 

- this is the more problematic decision and I can see both arguments re removing the tags, as well as the LOD annotations

WDYT, @SusanBrown

**Comment by SusanBrown** [comment]
Let's not remove the tagging from either the scraped candidates and the existing entities.

**Comment by ilovan** [comment]
@ajmacdonald , tagging is currently removed when someone removes actual entities (see Susan's comment) - can you please rectify.

Also, for nuance: 

NERVE tag and link candidates: remove tagging; do not add LOD annotation
NERVE link candidates: do not remove tagging (which was added by hand by a user) but do not add LOD annotation

**Comment by ajmacdonald** [comment]
a81093f0ebfc1179700952b2df7c0c47c98f6ff4

**Comment by SusanBrown** [comment]
Can this be closed then @ilovan ?

**Comment by ilovan** [comment]
yes;
