### ISSUE TITLE
Entity panel - "accept all" and "remove all" behaviour when scraped candidates list is filtered to a single entity type 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#162]
## Expected Behaviour
1. User filters to person
2. User hits "accept all" or "reject all"
3. All the candidates in the current view are accepted or rejected respectively
4. User is returned to the unfiltered view (because, either way, there are no candidates left to manage in the current, filtered view) 

## Current Behaviour
1. User filters to person
2. User hits "accept all" or "reject all"
3. All candidates are accepted or rejected (including the candidates that are filtered out from the current view)

**Comment by ajmacdonald** [comment]
310834cfe5599ac0f51799c75f842a7eb73bcce4

**Comment by ilovan** [comment]
confirmed

**Comment by ilovan** [comment]
confirmed on both production sites
