### ISSUE TITLE
TEI: allow for note tags with @type NOT research note, scholarnote or annotation

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#164]
FOr example:

The letter sample contains a note  @type="setting", which is perfectly legal in TEI but which cannot be reproduced in any letter document because anytime someone tries to create a note with a type set to something different than the radio buttons types, the custome type gets overwritten. 

The solution:
1. Allow for notes that are not LOD entities and open the type attribute

If tagging a note from the ribbon - keep current behavior.
If tagging a note from the tag dropdown,  treat like any other tag (do not create LOD, and allow any type value)

wdyt, @SusanBrown ?

**Comment by SusanBrown** [comment]
Agreed.

**Comment by ajmacdonald** [comment]
In general, if the user selects a tag from the tag dropdown do we want to use the standard tag dialog instead of the entity dialog?

**Comment by SusanBrown** [comment]
For tags that have corresponding entities, provide warning at top of tag dialog box IF and only if the editor was in RDF and XML mode:

Warning: you are creating a tag but **not** a corresponding entity/linked data annotation. Use the button on the tool bar to create a tag and an entity simultaneously.

**Comment by ajmacdonald** [comment]
4e5f854e237cf935c2221727c62c679ef91d829a

**Comment by ilovan** [comment]
confirmed

**Comment by ilovan** [comment]
confirmed on both production sites
