### ISSUE TITLE
NERVE: Orlando "clicking "Done" does not remove all the candidates remaining 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#167]
see for example all the entity tags with the `candidate="true"` attribute in https://dev-02.cwrc.ca/islandora/object/cwrc%3Af708f56f-9eef-4534-8b3b-ffa98ef6d89c/edit-cwrc

**Comment by ajmacdonald** [comment]
71aa9ecb29a0f8fa6924de8209df73a1d9087399

**Comment by ilovan** [comment]
confirmed on Production
