### ISSUE TITLE
Fix  all the security vulnerabilities

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#178]
- [ ] https://github.com/cwrc/geonames-entity-lookup/network/alerts
- [ ] https://github.com/cwrc/getty-entity-lookup/network/alerts
- [ ] https://github.com/cwrc/wikidata-entity-lookup/network/alerts
- [ ] https://github.com/cwrc/CWRC-Git/network/alerts
- [ ] https://github.com/cwrc/CWRC-GitServer/network/alerts
- [ ] https://github.com/cwrc/viaf-entity-lookup/network/alerts
- [ ] https://github.com/cwrc/dbpedia-entity-lookup/network/alerts
- [x] https://github.com/cwrc/CWRC-PublicEntityDialogs/network/alerts
- [ ] https://github.com/cwrc/cwrc-tei-entities-lookup/network/alerts
- [ ] https://github.com/cwrc/cwrc-entity-management-forms/network/alerts
- [ ] https://github.com/cwrc/CWRC-GitWriter/network/alerts
- [ ] https://github.com/cwrc/CWRCWriterDistributable/network/alerts

**Comment by ilovan** [comment]
@ajmacdonald , it's up to you to decide how do you want to go about it (i.e. fix high severity first across repos or deal with all severity levels within a repo at a time) - We definitely want the high and moderate severity ones fixed by the time we advertise the code to the larger DH community in early July.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms is no longer being used and has been replaced by https://github.com/cwrc/cwrc-entity-management-forms-static

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-GitServerClient has all the vulnerabilities patched except for one which is low severity. I can't fix it yet because a dependency that it depends on needs to be updated itself.

**Comment by ilovan** [comment]
Thanks @ajmacdonald 
Re https://github.com/cwrc/cwrc-entity-management-forms, can it be safely archived?

**Comment by ajmacdonald** [comment]
@ilovan yes it can

**Comment by ilovan** [comment]
@ajmacdonald , did you deactivate https://github.com/cwrc/CWRC-GitServerClient/network/alerts? Can you please explain?

**Comment by ajmacdonald** [comment]
@ilovan CWRC-GitServerClient got merged with cwrc-git-dialogs, so I archived the original repo

**Comment by ilovan** [comment]
right, forgot about that - thanks @ajmacdonald
