### ISSUE TITLE
Side-by side xml-image viewer: doesn't appear to be working in GitWriter.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#18]
Used the sample letter document (pb elements already included, I just added the facs attribute with values pointing to publicly available object datastreams in CWRC):

Example: https://github.com/ilovan/CWRC-Writer-Tests-3

Note that the xml is not valid because TEI lite, on which the CWRC TEI schema is based, does not recognize the facs attribute on pb.
This should not affect the visibility of the mages, though (I think).

**Comment by ajmacdonald** [comment]
It works on my local version. Where you're testing it probably doesn't have the functionality enabled.

**Comment by ilovan** [comment]
IN GitWriter, as can be inferred from the Example being in a GitHub repo.
My understanding is that the side-by-side functionality should be enabled in the new version of the GitWriter, please correct me if I am wrong, @jchartrand .

**Comment by ajmacdonald** [comment]
@ilovan this is now updated @ http://208.75.74.217/

**Comment by ilovan** [comment]
server indicated seems to be down.

**Comment by ilovan** [comment]
Works now but some comments/suggestions forthcoming.

**Comment by ilovan** [comment]
Just closed it because we should not probably move to prod before the additional tweaks I will shortly recommend.
