### ISSUE TITLE
Consider adding "fictional" option to place lookups so the user can add a tag but skip the linking

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#183]
## Expected Behaviour
This is by analogy with the fictional/real distinction for people, but there would be no location to look up.

**Comment by ajmacdonald** [comment]
There is already a "Tag Without Linking" button at the bottom of the lookup forms.

**Comment by ilovan** [comment]
Also, in the CWRC (TEI) entity forms for place, you have the option to specify whether a place is real or fictional. Once the fictional place entity is created, you can link to it like any other entity. 
Last but not least, WIkidata and DBPedia have instances of fictional places (https://www.wikidata.org/wiki/Q3895768).

Not to mention that, as @ajmacdonald said, you can tag without linking any named entity.

**Comment by SusanBrown** [comment]
So it sounds like it is unnecessary then.
