### ISSUE TITLE
Side-by-side xml-image viewer: how to display corresponding image for the first page in a document.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#19]
This is something we never considered. 

It affects all single page documents and the first page of every multi-page doc we want to use the side-by-side view for. 

Canonically, the first pb in a document should mark the break between page 1 and 2. 
The way we are setting things up in the side by side viewer, the facs attribute value on the first pb element in a document will provide the link for the image corresponding to the second page in the document. 

There aren't any good options for this  - to my knowledge - other that including a pb element at the beginning of a body element, which is not invalid per se but not very good form either.

@SusanBrown , any thoughts?

**Comment by SusanBrown** [comment]
Let's consult with James Cummings. Also need think about covers.

**Comment by ilovan** [comment]
we went ahead and used pb because pb does not stand for page break, but page beginning, which makes it appropriate to use at the beginning of any page, including the first. 
see http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-pb.html
