### ISSUE TITLE
Schema-required attribute handling: make it required in the tag dialog. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#195]
## Expected Behaviour
Something similar to what we implemented for the entity management forms: https://github.com/cwrc/cwrc-entity-management-forms-static/issues/29

## Current Behaviour
I don't believe we have handling for required attributes in place now, do we @ajmacdonald ?

**Comment by ajmacdonald** [comment]
Currently, required attributes are marked in red and have a red asterisk beside the field. There is nothing to prevent you from adding the tag if haven't filled in the required field, however.
![dev-cwrc-writer cwrc ca__](https://user-images.githubusercontent.com/882444/63283058-37d6c280-c27e-11e9-9707-f4295b87bb43.png)

**Comment by ilovan** [comment]
I'd say that we should probably change it so that you can't add the tag unless you tag it properly, with all the required attributes, but there may be editorial workflow cases where this is not possible, wdyt, @SusanBrown ?

**Comment by SusanBrown** [comment]
There will be times when an attribute can't be added right at the time when a tag was created so I think we should not prevent people from leaving required attributes blank, just as we should not prevent them from saving a doc if it is invalid.

**Comment by ilovan** [comment]
OK, in light of further discussion on this matter as part of devising an Orlando workflow within CWRC, we will go with using css to highlight to the user that something is missing in that tag, in addition to the validation error.
