### ISSUE TITLE
NERVE should be capitalized on the tab

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#198]
It's not clear that it's an acronym.

**Comment by ajmacdonald** [comment]
This was addressed a while ago on dev but hasn't made it into prod yet.
https://github.com/cwrc/CWRC-GitWriter/commit/458cf16bc6c6cc5d3849648c9998be2acbc11c4b
https://github.com/cwrc/CWRC-WriterBase/commit/78d957d99ba1793b2f0b8f4194316977aa62839e
