### ISSUE TITLE
NERVE schema support

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#220]

**Comment by ilovan** [comment]
see the most recent pull requests from Jeff on the NERVE repo

**Comment by ilovan** [comment]
https://github.com/cwrc/NERVE/pulls?q=is%3Apr+is%3Aclosed

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/4a054114a2ffadd543c3426fd920c4323153c75a
