### ISSUE TITLE
NERVE: Remove "Reject all" 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#228]
new behaviour for the "Done" button renders this button superfluous (see https://github.com/cwrc/cwrc-writerbase/issues/224)

**Comment by ajmacdonald** [comment]
I'm looking at the code and it may be that we want to keep this, because Reject All and Accept All use the current filter when performing the action. For example, you can choose to reject all organizations, and still retain the other entities.

**Comment by ilovan** [comment]
right - forgot about that (it makes sense to have it narrowed down to the current (filtered) view, as opposed to "Done" which basically obliterates everything. 

Will close this then
