### ISSUE TITLE
Save entity annotations as separate objects in GitHub

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#24]
Estimated time - one to two weeks

**Comment by jchartrand** [comment]
This would include a bunch of things like updating the OA format, deciding how annotations (once separated) should be bundled (if at all) and returned to the CWRC-Writer (maybe as a manifest), how versioning will work (noting that we've already done some work on this but we need to finalize).  This should be broken into several issues, but should first be talked through.  There are probably some other things that will come up as part of mapping this out.
