### ISSUE TITLE
Create two versions of the Git-Writer sandbox - one for showcasing/production, one for dev/testing

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#26]
It would be nice if this was implemented as soon as possible, and preferably before we send out the update to the CWRC-Writer external partners. 

@jchartrand and @ajmacdonald  - please sort out which one of you is going to do it.

**Comment by jchartrand** [comment]
When will the update be sent out?

Be sure to slot this appropriately into the prioritized list of todos.

**Comment by ilovan** [comment]
The update will hopefully be sent out at the beginning of next week.

**Comment by ilovan** [comment]
Update: please assign the instance at http://208.75.74.217/ as the showcasing/demo version and roll it back to the relatively stable version before Andrew included the side-by-side viewer. 

Create a new instance for the dev-testing version and install the most up-to date code there. 

The reason why I am asking you to do so is because Jeff has just started redirecting http://cwrc-writer.cwrc.ca/ to http://208.75.74.217/ and this is the URL that will be included in the Update to the partners.

**Comment by jchartrand** [comment]
Hopefully it is easy to set up a second instance, but I would still assume there could be delays. If for whatever reason it requires talking with the DAIR people it could take longer, and we won’t start on this until Monday.

**Comment by ilovan** [comment]
Let's hope it will work out smoothly. It would be highly desirable if the two versions would be in place by the end of this week. Please let us know if you want us to lean on CANARIE.

**Comment by ajmacdonald** [comment]
@ilovan http://208.75.74.217/ is now using the pre-side-by-side version

**Comment by SusanBrown** [comment]
@ilovan When you're back could you please clarify for @ajmacdonald what was unstable about the side-by-side version?

**Comment by jchartrand** [comment]
Two new versions are in place.

 http://208.75.74.217  - Production
 http://208.75.74.225  - Development

**Comment by ilovan** [comment]
@ajmacdonald 
@jchartrand 

Could you please record your time for this issue and the other issues you've been working on during the second half of December? Putting the hours in the label of the issue should work: e.g. (J-10.5, A-6.5)

To bring Andrew up to speed, Susan and I agreed with James that it makes sense for you folks to keep track of development time on each GitHUb issue and for us to compile said time for the CANARIE time sheets.

**Comment by ajmacdonald** [comment]
@ilovan you'd like us to add labels whose content is the number of hours we've worked on an issue?

**Comment by ilovan** [comment]
Sorry - I meant putting the hours in the **title** of the issue (makes it easier to add up)

**Comment by jchartrand** [comment]
I think you’ll still want to add a label of some sort, though, so you can more easily find/group the issues later?  Maybe this would also indicate the Canarie period (quarter or whatever), so like:  CanB2018Q2  (for Canarie grant B 2018 Q2)?  I assume you’ll add that.

Where would you like us to record hours for things like meetings or general emails or administrative stuff, or time spent on things that don’t fall neatly into an issue?

And for things where there isn’t yet an issue, like the emailing this past week with Jonathan, should we create a new issue ourselves, or ask you to create the issue (and the corresponding label that would categorize it as canarie 1 or 2, or whatever)?

In December I hadn’t been tracking specifically which hours had gone into which issue, so even though I do have a pretty good idea where they went, it will be an estimate for the last few weeks.

**Comment by ilovan** [comment]
@jchartrand 
I will add the labels when I am preparing the reports for the two grants, so please don't worry about adding them yourselves (I thought the point of us employing GitHub for time reporting was precisely so that you and Andrew don't need to bother with figuring out wether a task is CANARIE 1 or 2.) The reason why I would not add the grant label from the moment when the issue is created is because sometimes it's kind of blurry whether a task should go to one grant or the other  and in those cases I will likely take into account budget considerations when making that decision, based on how the report is shaping up. 

For non-issue time, I will create a card for each of you in a new column in the CWRC-Writer Project, called "Time keeping". Please use those cards to record any administrative activity, like emails, meetings, etc. 

If there is anything that you are working on that doesn't have an issue yet and you feel one would be good to keep track of thing other than through email (e.g. work for iSicily), please go ahead and create an issue (since you are the one working on it, I assume you know the details of it and also why that specific work is needed, so it does not make sense to have an additional step in which you ask me to create the issue, with all the explanations and back and forward this would likely entail. 

It's OK if December is not too specific, as long as you have a pretty good idea of where the time went. 

I will take this conversation and synthesize it into a project card called "Timekeeping instructions" that I will place in the "Reference" list created last week in the CWRC-Writer project.

**Comment by ilovan** [comment]
@jchartrand 
@ajmacdonald 

For the moment (until early next week) could you please continue to keep track of your time the way you've done so last year? 

I am trying to implement a solution that would work across the entire CWRC GitHub organization and apply to all the CWRC collaborators that have to report their time for CANARIE, but I need to consult with Jeff when he comes back to work with us next week before I proceed. 

Thanks for your patience.
