### ISSUE TITLE
Assign human readable URLs to development version of the CWRC-Writer sandbox.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#27]
I suggest http://dev-cwrc-writer.cwrc.ca/

**Comment by jefferya** [comment]
Wasn't this already done on Dec 15th via with the DNS entry for "cwrc-writer.cwrc.ca" or am I misunderstanding the ticket?

**Comment by ilovan** [comment]
There are two instances of Git-Writer, @jefferya 
http://208.75.74.217 - Production
http://208.75.74.225 - Development

cwrc-writer.cwrc.ca is assigned to the production server

**Comment by jefferya** [comment]
Added to the DNS. Should be available in about an hours as the DNS entry propagates throughout the internet.

**Comment by ilovan** [comment]
It's alive!!!
Thanks @jefferya
