### ISSUE TITLE
Adding keyword entity is broken

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/CWRC-WriterBase#29]

**Comment by SusanBrown** [comment]
Mihaela writing to consult

**Comment by ilovan** [comment]
Decision: 
Use : <seg ana=”URI URI URI [or] #categoryID in header or taxonomy.xml#categoryID in a separate document]”>keyword</seg>

Also, added to https://docs.google.com/document/d/1swmwJdgqxyMmd6YIhq6nPuKA7Na5EadYG6xVk4ua3MY/edit#bookmark=id.ahr2xbcegjjb

Detailed discussion:
https://docs.google.com/document/d/1Ri8Vyxq-werk7d4aFW__PclnckXYQ7FO_b07VV9UPqA/edit

**Comment by ilovan** [comment]
also, @ajmacdonald , since the @ana attribute is highly recommended, could we have a warning in place if the user saves the keyword without providing it?
Something like: 
"It is recommended to reference a taxonomy when employing keywords. Are you sure you want to save your keyword without linking it to a taxonomy term?"

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/be09e571399d9b0652ddf4f7d965714ddc1a9a2f

**Comment by ilovan** [comment]
works as described, thanks @ajmacdonald

**Comment by SusanBrown** [comment]
Instructions for this need to be clearer. If I understand what is supposed to happen correctly, then I suggest something along these lines:

> A human-readable keyword is preferably linked, using the "ana" attribute, to a controlled vocabulary. Click "add link" to add a URL for your term or "skip link" to save as is.

**Comment by ilovan** [comment]
@ajmacdonald , please see Susan's last comment above. 

Behaviour for "Add link" - return to the entity popup with the ana attribute selected
Behaviour for "skip link" - save keyword without any reference to a controlled vocabulary.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/689b113836d72bd62b793f4e5c8c37415b3b4597

**Comment by ilovan** [comment]
confirmed on dev-cwrc-writer.ca

**Comment by ilovan** [comment]
confirmed on both production sites
