### ISSUE TITLE
New document saving mechanism

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#3]
Appears not to work:

![screen shot 2017-09-06 at 11 44 40 pm](https://user-images.githubusercontent.com/6600070/30148883-a4f8ad8a-9362-11e7-872a-bf3f373bdae1.png)
![screen shot 2017-09-06 at 11 45 08 pm](https://user-images.githubusercontent.com/6600070/30148884-a4f8d2ec-9362-11e7-8360-17392731bcd6.png)

Saving freezes.

**Comment by jchartrand** [comment]
Should be good now.
