### ISSUE TITLE
load hangs

### ISSUE THREAD

**Issue by jchartrand** [cwrc/CWRC-WriterBase#30]
When trying to load the letter.xml template in the GitWriter (cwrc-writer.cwrc.ca) in Safari on a Mac, it hangs at this point:

![pastedgraphic-2](https://user-images.githubusercontent.com/547165/35004110-efae553e-fabc-11e7-894c-3c3e4fd39914.png)

with this underlying error:

<img width="891" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/547165/35004163-0c410804-fabd-11e7-8b5c-b331fac186bb.png">

the code for which, running in the browser, is:

Mapper.getXpathResult = function (xmlContext, xpath, nsPrefix) {
    nsPrefix = nsPrefix || '';
    var nsUri = xmlContext.namespaceURI;
    if (nsUri === null && nsPrefix !== '') {
        // remove namespaces
        var regex = new RegExp(nsPrefix + ':', 'g');
        xpath = xpath.replace(regex, '');
    }
    var nsResolver = function nsResolver(prefix) {
        if (prefix == nsPrefix) return nsUri;
    };

    var result = $(xmlContext).xpath(xpath, nsResolver)[0];
    return result;
};

which doesn't actually match what's in the CWRC-WriterBase master branch, so I'm guessing it might be new code in a local branch that was deployed to the server

**Comment by ajmacdonald** [comment]
This is fixed [here](https://github.com/cwrc/CWRC-WriterBase/commit/3464a9e39b4a933ad6385f930af637e02ca9570b) but the code on the server hasn't been updated.
