### ISSUE TITLE
Entity lookups https fail

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#33]
On Wed, Jan 17, 2018 at 5:48 PM, Andrew MacDonald :

I'm trying to update CWRC-Writer on dev-05 and have it mostly working. One issue though is the islandora_cwrc_writer_get_ absolute_url method (https://github.com/cwrc/ Islandora-CWRC-Writer/blob/ npmbuild/includes/utilities. inc#L1265 ) which is used to get the CWRC-Writer baseUrl, the viaf lookup url, etc. It doesn't return https urls when accessing dev-05 through https. Would you be able to modify it so that it determines whether or not https is required?

On Thursday, January 18, 2018, 12:58:05 PM EST, Jeffery Antoniuk :

Could you provide more information? 

* Can you describe the steps needed to reproduce the problem you are experiencing?
* Where should I be looking to see that the wrong baseUrl and viaf urls?

On Thu, Jan 18, 2018 at 11:17 AM, Andrew MacDonald :

To reproduce:
1) load up a document on dev-05, making sure you access the site through https, e.g. https://cwrc-dev-05.srv.ualberta.ca/islandora/object/cwrc%3Aaa6d5d89-18c0-4a77-9e30-312038645287/edit-cwrc 
2) select some text in the edtior and try to tag it as a person entity
3) if you have the browser's developer console open, you'll see error messages relating to mixed content:

Mixed Content: The page at 'https://cwrc-dev-05.srv.ualberta.ca/islandora/object/cwrc%3Aaa6d5d89-18c0-4a77-9e30-312038645287/edit-cwrc#cwrc:aa6d5d89-18c0-4a77-9e30-312038645287' was loaded over HTTPS, but requested an insecure resource 'http://viaf.org/viaf/search?query=local.personalNames+all+%22mp%22&httpAccept=application/json&maximumRecords=5'. This request has been blocked; the content must be served over HTTPS.

On Thu, Jan 18, 2018 at 4:39 PM, Jeffery Antoniuk:

I've attached an image of what I'm experiencing. 

The codebase has changed in significant ways since I last looked so everything is new and I've been out of the loop on many of the changes thus this maybe a stupid question on my part. I wanted respond asap so I didn't try to familiarise myself with the changes so this question might be uninformed. 

The code I've looked at for the errors I'm receiving appears to be hard-coded in JavaScript (build/js/app.js) for "lookup.dbpedia.org", "vocab.getty.edu" and "viaf.org". I'm not sure how the npm build works, do these properties get overridden elsewhere? 

The GitHub line you mention appears to be return https urls for other items so it might not be the culprit though I'm having trouble tracking down the how the aforementioned url's are specified and flow through the code.
(https://github.com/cwrc/Islandora-CWRC-Writer/blob/npmbuild/includes/utilities.inc#L1265

**Comment by jchartrand** [comment]
Hopefully once we've switched the entity calls to run through an HTTPS proxy, these Mixed Content errors will go away.

But, after reading this it occurred to me that maybe it makes more sense for Jeff to create the HTTPS proxies to the two HTTP entity sources (getty - http://vocab.getty.edu, dbpedia - http://lookup.dbpedia.org) on the cwrc server alongside the other existing proxies (like the validator -http://validator.services.cwrc.ca/validator/index.html, https://validator.services.cwrc.ca/validator/index.html). This would keep all the proxies in the same place.  As with the validator we'd need CORS enabled.

And, if Jeff thinks it’s okay, also create a proxy to allow fetching http-only schema and css files - Jeff, this is something Mihaela is going to talk to you about (or may have already).

**Comment by jefferya** [comment]
@jchartrand 

I think this is setup as per your examples. I'm not sure how to test.

Also, can a note be added to the documentation noting the need for the proxies? I'm not sure where is best.

**Comment by jchartrand** [comment]
Thanks Jeff.

Mihaela is probably best to decide where that should be documented, although I will at least document it in our getty and dbpedia npm packages.

**Comment by ilovan** [comment]
Working in dev-cwrc-writer.cwrc.ca now; 
Re documenting, what were you referring to, @jefferya , documenting the need for HTTPS proxies for some of the entity lookups or the need for HTTPS proxies for http schema and css referenced. 

If the former, I think it should sit in the readme file of the specific lookups. 
If the latter, probably in the documentation (/readme) for GitWriter.

**Comment by ilovan** [comment]
@jchartrand , 
can you please confirm once the technical documentation has been added to the proper locations?

**Comment by jchartrand** [comment]
I documented the calls in the READMEs of:

https://github.com/cwrc/dbpedia-entity-lookup/blob/master/README.md

and

https://github.com/cwrc/getty-entity-lookup/blob/master/README.md

when I made the changes to the code.

**Comment by ilovan** [comment]
@jchartrand  - just a gentle reminder to update the proxy setting documentation to include the work done to add proxies for the entity previews.

**Comment by jchartrand** [comment]
Done.
