### ISSUE TITLE
Should required attributes be enforced when adding a tag?

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/CWRC-WriterBase#34]
For example, should the user be able to create a graphic tag with no url attribute?![required.png](https://images.zenhubusercontent.com/5a6124b24b5806bc2bc3566f/a3e687bb-202a-433b-9140-6eae1d09c322)

**Comment by SusanBrown** [comment]
My guess is that we might want to add a pop up a warning that a required attribute is missing, but that we don't want to absolutely require.

We will consult with users about preferences.

**Comment by SusanBrown** [comment]
I have consulted with users and confirmed that we want the status quo: users should be able to save invalid documents. Alerting them to the invalidity of documents upon save, which I believe is currently in place, is helpful and should be retained.
