### ISSUE TITLE
Organization button leads a mislabelled organization lookup?

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#35]
Using Gitwriter, but I presume this is a problem with the base code.

Selecting text and then click on the entity button for organizations loads a lookup box that says "Find a Person". However, the results returned are slightly different than if you use the Person button, so it may simply be labelled wrong.

**Comment by jchartrand** [comment]
I can't reproduce this on dev (https://dev-cwrc-writer.cwrc.ca).

**Comment by ilovan** [comment]
Can't reproduce on prod either (https://cwrc-writer.cwrc.ca).
I believe it may have been a fluke . 

@SusanBrown , are you still getting the same error? If not, let's close this issue.

**Comment by SusanBrown** [comment]
Can't see this behaviour any more.
