### ISSUE TITLE
Note tags rendering inconsistently within mini-CWRC-Writer

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#40]
![image](https://user-images.githubusercontent.com/545952/35587364-94a058b2-05cb-11e8-9013-0b37e91eb2df.png)
Actions:
in Sample Letter file, clicked on"Bergen", clicked on Citation button, selected first option, changed settings in mini-CWRC-Writer to show tags, clicked twice on bibl --noticed inconsistency in Note tag.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/647fc4f95636a5327ec8443a422d188fcd707d91

**Comment by ilovan** [comment]
fixed in dev-6 and Prod Git-Writer
