### ISSUE TITLE
Weird, intermittent error when trying to right-click in the text area in the dev Git-Writer

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#42]
Error happens on a Mac, in Chrome, when I right click (I have two digit click enabled for that). When it does happen, the word I clicked on gets selected. 

![Screen Shot 2018-01-31 at 11.34.11 AM.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/3906a464-a077-48c0-b6eb-1283901b00fb)

**Comment by ajmacdonald** [comment]
Should be fixed by this https://github.com/cwrc/CWRC-WriterBase/commit/3cf716b23b50e9023dc1ceb17214f2b2c01d4fdc but please double check on dev

**Comment by ilovan** [comment]
NOpe, doesn't happen anymore - I believe it's fixed.

**Comment by ilovan** [comment]
Seems to be fixed on dev-06 and Prod Git-Writer as well.
