### ISSUE TITLE
Side-by side: if the images are pngs with transparent backgrounds, the images load on top of each other

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#43]
See example:

https://github.com/ilovan/Jan-2017-SideBySide-Test

Ideally, if png images (or any other transparent background images) shown, either load them one at a time or provide background upon loading.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/89da5cd94e3d7afba5c391a6af567e769225239c

**Comment by ilovan** [comment]
is this done, @ajmacdonald ? (can you move the issues that have been dealt with into the QA pipeline, please?)

**Comment by ajmacdonald** [comment]
@ilovan yes I will

**Comment by ilovan** [comment]
Confirmed

**Comment by ilovan** [comment]
fixed in both dev-06 and Prod Git-Writer
