### ISSUE TITLE
Side-by-side: Modify visibility rules for the right-side (image) panel

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#44]
1. If pb with @facs value exist in the loaded document, expand panel upon loading the document.

2. If pb exists but no @facs or value defined in the loaded document, have the panel collapsed by default when loading the document; keep the "No URI found for @facs" warning in, in case users expand the panel.

3. If no pb element available in the loaded document, have the panel collapsed by default when loading the document; provide a "Provide page breaks with facs attributes pointing to image URLs to display the corresponding images/scans for pages in this doument" warning in the image panel , in case users expand it.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/88977a983840191ab7ab6c421e7c6133a669d6ad

**Comment by ilovan** [comment]
1. works as described: https://github.com/ilovan/Jan-2017-SideBySide-Test
2. no: see the simple letter template, where we have: 
`<pb n="<---whatever the number is-->">`
3. works as described: https://github.com/ilovan/Side-by-side-test-no-pb- (but see

**Comment by ilovan** [comment]
Will return to "in-progress" for now

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/4c9c91f06b758467b913ef9cdb6946797fc26627

**Comment by ilovan** [comment]
confirmed on dev-CWRC-Writer

**Comment by ilovan** [comment]
@ajmacdonald, in prod GitWriter Chrome, the user still gets all three panels opened when loading the letter template. (not the case in Firefox though, or in dev GitWriter in Chrome, though) 

Will move this issue back to production because of this.
