### ISSUE TITLE
"Undo" disable completely or fix

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#46]
Using the browser undo currently creates issues in both Git-Writer and Islandora -integrated versions:

GitWriter (I added some text and then tagged as an entity; I used the command+z to undo the tagging and the string added and this is the result: the persName tag is still showing in the structure panel and the entity is still showing up in the entity panel, though they are no longer visible in the raw view of the document)
![Screen Shot 2018-02-05 at 10.35.35 AM.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/ddd8da87-826e-4638-bcc4-7030c2e2ff19)

Islandora CWRC-Writer  (I did a multitude of operations, mainly copying and deleting paragraphs before I did a couple of "undo" s: this is what temporarily showed up in my view: entity panel - no P, all its children wrapped under heading, text area - p visible; after doing a couple of additional edits the P reappeared in the structure panel as well)

![Screen Shot 2018-02-05 at 10.31.29 AM.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/6304c4ba-0114-4434-aa8b-948d4f37545e)

I believe that we have two options here:

Preferable: fix Undo and then https://github.com/cwrc/CWRC-WriterBase/issues/16
StopGap: disable Undo (or make it have no effect on the CWRC-Writer)

**Comment by ajmacdonald** [comment]
I'm unable to reproduce this; it might be a Mac specific issue.

**Comment by ilovan** [comment]
Behaviour consistent in Firefox and Chrome. 

The wrapping of the children of P under the previous heading is consistent with the "delete" behaviour recorded here: #41 

The rest (i.e. tags still showing in the structure panel after tagging undone) may be a caching problem?

**Comment by ajmacdonald** [comment]
@ilovan what do you mean by "the wrapping of the children of P under the previous heading is consistent with the "delete" behaviour"?
Can you please provide more specific steps for reproduction?

**Comment by ilovan** [comment]
See my detailed steps in https://github.com/cwrc/CWRC-WriterBase/issues/41 this morning, specifically step 3b. 
 
Is this useful?

**Comment by ajmacdonald** [comment]
@ilovan ok I think I understand about the wrapping.
I still can't reproduce this though. Can you please give me specific steps?

**Comment by ilovan** [comment]
Can you reproduce the Git Writer bug though? I'll try to reproduce the dev-05 one but I am afraid  - as I said - that I don't remember all the steps I took before the undo. Will keep you posted.

**Comment by ajmacdonald** [comment]
@ilovan I can't reproduce the GitWriter bug in Chrome or Firefox on Windows

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/c4915a72d7ccb991cad201c3866bd01433c71ff1

**Comment by ilovan** [comment]
I can't reproduce anymore, either on beta or on dev-06
