### ISSUE TITLE
Reverse order of tag selection functionality

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#47]
Make tags italic and select content only upon first click. 
Make tags bold and select content and tags upon second click.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/c097b80b4ed1eb9c9635e97918c6b52beecf5f9d

**Comment by ilovan** [comment]
confirmed

**Comment by ilovan** [comment]
confirmed on dev-06 and prod Git-Writer
