### ISSUE TITLE
StructureTree: copying nodes using drag n drop results in duplicate IDs

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/CWRC-WriterBase#48]
Newly copied tags have proper IDs in the editor, but duplicate IDs in the tree.

**Comment by ilovan** [comment]
@ajmacdonald , is this something that can be tested on the user end?

**Comment by ajmacdonald** [comment]
1) copy nodes in the structure tree
2) in the tree, select/click each copied node in turn
3) if each copied node selects the same (initial) node in the editor, then the issue is unresolved

**Comment by ilovan** [comment]
seems to be fixed in prod Git-Writer and dev-06
