### ISSUE TITLE
TEI CSS conflict in rendering note tags

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/CWRC-WriterBase#49]
Certain rules in the TEI CSS prevent the display of ```<note>``` opening tags.

![note tag.png](https://images.zenhubusercontent.com/5a6124b24b5806bc2bc3566f/14468eda-f06e-4c0d-8afe-5ae71d952e8a)

The relevant rules seem to be:
```
note[type]:before {
    content : attr(type) ': ';
}
opener note:before {
    content:'';
    font-variant:normal;
}
opener note[type]:before {
    content:'';
}
```

**Comment by SusanBrown** [comment]
I've put this in the Mellon demo release but it should only be undertaken if this is a relatively simple fix, unless this would contribute towards the reworking of the rendering of notes generally.

**Comment by ilovan** [comment]
@ajmacdonald , what should be in there so that the content of the notes is visible in a popup but not in the normal flow of text in the editing/reading area?

**Comment by ajmacdonald** [comment]
@ilovan if you remove these two entries, it should fix things
```
opener note:before {
    content:'';
    font-variant:normal;
}
opener note[type]:before {
    content:'';
}
```

**Comment by ilovan** [comment]
Done. 
https://github.com/cwrc/CWRC-Schema/commit/df137b801d9239e00291f9637857a7599acb1078

**Comment by ilovan** [comment]
Still having the same issue with the TEI letter template:

`
<opener>
					<note type="setting">
						<p>Some opening note describing the writing setting</p>
					</note>
					<dateline>
						<date>Some date (set date value in attribute).</date>
					</dateline>
					<salute>Some salutation, e.g. "Dearest <persName annotationId="ent_62" cert="definite" type="real" ref="http://viaf.org/viaf/39569752">Miquel</persName>"</salute>
				</opener>
`

**Comment by ajmacdonald** [comment]
@ilovan this is what I'm seeing on dev-cwrc-writer.cwrc.ca
![note tag](https://user-images.githubusercontent.com/882444/38628809-46ae3754-3d80-11e8-82e6-b254157c4cba.png)

**Comment by ilovan** [comment]
You're right, it is fixed on dev-CWRC-Writer, but since you moved the issue to Review/QA 2 I assumed it was already pushed to prod GitWriter and tested it there :)
Will move to Deploy to Git-Writer

**Comment by ilovan** [comment]
fixed on all instances
