### ISSUE TITLE
Side-by-side: image view layout in Firefox crams different elements 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#51]
![Screen Shot 2018-02-08 at 11.12.45 PM.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/a5af1e72-4545-46ee-9bae-f7767e24c25e)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/4c9c91f06b758467b913ef9cdb6946797fc26627

**Comment by ilovan** [comment]
still not pushed to prod Git-Writer

**Comment by ilovan** [comment]
fixed in prod Git-Writer and dev-06
