### ISSUE TITLE
Side-by-side: Image viewer image navigation buttons, when clicked on, don't alter the pagination at the top, though they do change the page

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#52]
![feb-09-2018 12-15-59](https://user-images.githubusercontent.com/6600070/36045490-1e624370-0d93-11e8-88c5-b732f2552d58.gif)

**Comment by SusanBrown** [comment]
Nice cats ;)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/4c9c91f06b758467b913ef9cdb6946797fc26627

**Comment by ilovan** [comment]
Confirmed on dev-cwrc-writer.cwrc.ca

**Comment by ilovan** [comment]
fixed in dev-06 and Prod Git-Writer
