### ISSUE TITLE
Long entity labels in the entity panel run into the next entity in the list

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#53]
Repo: https://github.com/ilovan/Jan-2017-SideBySide-Test
Both Firefox and Chrome, on a Mac

![feb-09-2018 12-32-31](https://user-images.githubusercontent.com/6600070/36046191-55ee5aa2-0d95-11e8-8afe-19eb64e4dc3d.gif)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/b13fddfddd4447a9a6cdb9144b94a896981ae4c0

**Comment by ilovan** [comment]
@ajmacdonald , is this ready for testing? If so, can you please move in the appropriate pipeline?

**Comment by ilovan** [comment]
@ajmacdonald , is there a way of fixing this without truncating the title?


![apr-10-2018 21-08-35](https://user-images.githubusercontent.com/6600070/38594430-6b2b7362-3d03-11e8-9c46-11b3cec8780b.gif)

**Comment by ajmacdonald** [comment]
@ilovan yes there should be

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/b179139c9626830ccf06dfa031fb3a5f714c1a27
@ilovan I've updated dev-cwrc-writer.cwrc.ca with the new label handling

**Comment by ilovan** [comment]
confirmed

**Comment by ilovan** [comment]
work complete and deployed
