### ISSUE TITLE
Side-by-side: If no pb and user expands the image viewer, the message does not wrap and the width expands to text length. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#54]
https://github.com/ilovan/Side-by-side-test-no-pb-

![Screen Shot 2018-02-09 at 12.54.51 PM.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/82b462f8-11a7-4fef-b72c-dc7f54125561)

**Comment by ilovan** [comment]
Further more, this weird layout is cashed, so if next I load a different repository (say one that has images, like https://github.com/ilovan/Jan-2017-SideBySide-Test), this is what happens:

<img width="1425" alt="screen shot 2018-02-09 at 1 26 57 pm" src="https://user-images.githubusercontent.com/6600070/36048651-2d97584e-0d9d-11e8-9daa-e1e8f357838d.png">

**Comment by SusanBrown** [comment]
If doable it would be nice to fix before Mellon release because so weird, but not adding because relatively low priority.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/4c9c91f06b758467b913ef9cdb6946797fc26627

**Comment by ilovan** [comment]
confirmed on dev-cwrc-writer.cwrc.ca

**Comment by ilovan** [comment]
Fixed in Prod GitWriter; the issues in the Islandora integrated CWRC-Writer are more complex and described in https://github.com/cwrc/Islandora-CWRC-Writer/issues/23
