### ISSUE TITLE
Do not add a p by default inside the note in the mini-CWRC-Writer

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#55]
@ajmacdonald , what basis are you adding the 
`<p></p> `
inside the note element in the  mini-CWRC-Writer? The reason I am asking is because notes are not required to contain paragraphs  and they rarely do in TEI.

I would vote for adding by default just the note element and allowing users to choose how to structure them.

@SusanBrown , what's your take?

**Comment by SusanBrown** [comment]
Agreed, then: if a note is valid with no paragraph tag then let’s go with what Andrew suggests for TEI.

Mihaela, could you just double check in the Orlando/CWRC schemas, though? Paragraph tags can be used within notes and I fear they may be required.

**Comment by ilovan** [comment]
Just to make sure we are on the same page, @SusanBrown , I am not sure I understand what you mean by: "if a note is valid with no paragraph tag then let’s go with what Andrew suggests" (maybe you meant what I suggested?)

Re whether or not the Orlando and/or CWRC schemas require the P tag inside the note tag , the answer is "yes" for Orlando and "no" for CWRC. However, the question seems moot to me:

1. The element for the note entity is different in TEI (note) than in CWRC or Orlando(RESEARCHNOTE, SCHOLARLYNOTE)
2. I don't believe CWRC-Writer is set up to automatically add the required children when the user adds the parent that requires them. Am I right to assume, @ajmacdonald , that in this particular case you are hardcoding the addition? 
If I am right about this, then I don't see why we would want to make a special case of the note (users could always validate the doc and correct the error if they do not ad the <P> for the Orlando schema).

**Comment by SusanBrown** [comment]
I think there was something historical that made it make sense to add the p tag at some point, but I cannot recall what it was.

I thought we were talking about any notes within mini CWRC-Write.

If we are talking about TEI NOTE tags only only, then let us definitely remove the P tag.

**Comment by ajmacdonald** [comment]
@ilovan re: 2, yes, I'm adding the p tag manually, see https://github.com/cwrc/CWRC-WriterBase/blob/master/src/js/schema/tei/xml/note.xml for the template.

I will remove the p tag.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/bfd5ead802026d9638befec7bbc17f15d70ce671

**Comment by ilovan** [comment]
implemented in Prod GitWriter and dev-06
