### ISSUE TITLE
Mini-Cwrc-Writer: One "Delete" when current element = p and empty removes the entire xml structure

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#56]
TEI Letter template, Mac, both Chrome and Firefox:
 
![feb-09-2018 13-38-40](https://user-images.githubusercontent.com/6600070/36049967-eec1d9f0-0da1-11e8-94c6-2dc67657d44a.gif)

**Comment by ilovan** [comment]
related to https://github.com/cwrc/CWRC-WriterBase/issues/41, if that's of any help

**Comment by SusanBrown** [comment]
Add to Mellon release only if confident it would be a quick and reliable fix.
