### ISSUE TITLE
Add names of authors to CWRC-Writer poem templates

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#57]
Add "P.K. Page" to the sample poem and poem template as a new line under the title.

**Comment by ilovan** [comment]
Added for the sample poem

@SusanBrown  where exactly do you want me to add P.K.Page to the poem template? the short poem in that file is by Floris Clark McLaren.

**Comment by SusanBrown** [comment]
Oops. My bad. Please add the author’s name in a separate line below the title.

On Feb 11, 2018, at 12:16 PM, Mihaela Ilovan <notifications@github.com<mailto:notifications@github.com>> wrote:


Added for the sample poem

@SusanBrown<https://github.com/susanbrown> where exactly do you want me to add P.K.Page to the poem template? the short poem in that file is by Floris Clark McLaren.

**Comment by ilovan** [comment]
Done.
