### ISSUE TITLE
URLs

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#58]
Prod site: https://cwrc-writer.cwrc.ca/
Dev site: https://dev-cwrc-writer.cwrc.ca

**Comment by ilovan** [comment]
@SusanBrown , I am closing this issue to clear the tray; I have created a Tools reference file in the CWRC technical documentation @ https://github.com/cwrc/tech_documentation/blob/master/Tools-reference.md
