### ISSUE TITLE
Limit  "Delete"  to the content of the current tag (allow deleting tags/ modify the structure of the document from the tag structure panel only)

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#59]

**Comment by ajmacdonald** [comment]
This is now deployed on https://dev-cwrc-writer.cwrc.ca/

**Comment by ajmacdonald** [comment]
6976b7341c8665add73d3632f346cd02d869f6dd

**Comment by ilovan** [comment]
looks good - Can you please implement on dev-02?

**Comment by ilovan** [comment]
@ajmacdonald , I just tested this again on test-01 and it looks like if you start to delete text in a p tag, then encounter an entity tag, you can delete to the end of the entity tag:
see:

![Apr-01-2019 16-02-10](https://user-images.githubusercontent.com/6600070/55362657-dad99c00-5497-11e9-8ed9-001f9e0c8fd8.gif)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/20a78cc7193c5b7db9c1ad226037adc274ac78e1

**Comment by ilovan** [comment]
confirmed on both production sites
