### ISSUE TITLE
Add warning when changing to a schema with a different root element.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#62]
When changing to a schema with a different root element 9from within CWRC-Writer settings) - wanr user that "Root element required by the selected schema is different from the root element of the current document. Applying this schema change will cause a document loading error"

**Comment by ajmacdonald** [comment]
@ilovan should this be a yes/no confirmation or just a warning message?

**Comment by ajmacdonald** [comment]
5bc8589ac70818bb8cb1f0feb054624e072b758a

**Comment by ilovan** [comment]
confirmed

**Comment by ajmacdonald** [comment]
19d5c74a1d510d8b922b1dec515762adecf19254

**Comment by ilovan** [comment]
confirm on all versions
