### ISSUE TITLE
Change and make consistent the right-click menu for entities in structure panel and text area

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#63]
Make right-click option in text area identical to right-click option in the structure panel.

![Screen Shot 2018-02-15 at 3.08.44 PM.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/6acf5c16-cb03-44ab-9a2c-d2e5e20b2347)

**Comment by ajmacdonald** [comment]
@ilovan duplicate of #7 ?

**Comment by SusanBrown** [comment]
Related to #37?

**Comment by ajmacdonald** [comment]
Sort-of related to #37, yes

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/b9e4dd59f1dc2358a9b2ea03c430e7998f329ea7

**Comment by ilovan** [comment]
duplicate, will close
