### ISSUE TITLE
Hide the first pb in a doc

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#65]
![Screen Shot 2018-02-18 at 2.02.45 AM.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/2a6d3c4f-ec33-40ec-98dd-1689dc2eeebe)

**Comment by ilovan** [comment]
If this is going to help only if all pb are siblings, then there are not a lot of use cases for it - the first pb would likely have body as parent, while subsequent ones would fall within paragraphs, divs, biblists, etc. Is there another workaround that woudl apply in all cases - even if not a css-driven one?

**Comment by ajmacdonald** [comment]
@ilovan yes, a JS solution is possible

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/e429144434bd6351bad81d170bdb18e3d9b80bae

**Comment by ilovan** [comment]
This is fixed in both production Git-Writer and dev-06 cwrc-writer.
