### ISSUE TITLE
Wrap the markup view of the text that appears in the lower pane

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#66]
Happening in gitwriter with chrome Version 63.0.3239.132 (Official Build) (64-bit) on Mac 

![image](https://user-images.githubusercontent.com/545952/36408088-187d4540-15d1-11e8-84c1-d6cc399c41ec.png)

**Comment by SusanBrown** [comment]
Consult with REED editor about show markup options.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/ba1f0a08d71520d12a102acf6e6bd602b322df81

**Comment by ilovan** [comment]
confirmed

**Comment by ilovan** [comment]
work complete and deployed
