### ISSUE TITLE
Make content of scholarly notes and citations visible to users in the editing mode in a mouse-over pop-up

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#67]
This would be especially useful for Git-Writer users who don't have a read-only view.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/6817419cb5c946b0b7c8c085669132c8a8906555

**Comment by ilovan** [comment]
This seems to be implemented on both dev and prod GitWriter, as well as the editing mode on dev-06. 
Closing it for now.
