### ISSUE TITLE
Inconsistent selection of validation errors in the text area

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#72]
Chrome, Mac.

Repository tested: https://github.com/ilovan/NERVE--processed-ultra-short-TEI
To reproduce: validate document, then start selecting validation errors from the bottom of the list up, then alternating between the two "entities" (not RDF or CWRC_Writer entities but NERVE generated ones - ignore the wanky structures - Ed is dealing with those).

Just focus on what get's selected or not in the text area when you click on a certain validation error. 
My hunch is that some types of validation errors do select the xpath in the text area, while others don't.

**Comment by ilovan** [comment]
Highest priority, @ajmacdonald , thanks.

**Comment by ajmacdonald** [comment]
The problem seems to stem from some of the xpaths not pointing to valid locations in the document. So, when you click on the error, it doesn't change the selection because it can't find the target.

Some examples from your test document:
```/TEI/teiHeader[1]/fileDesc[1]/titleStmt[1]/title[1]/div[2]/div[1]```
the location it almost refers to:
```<titleStmt><title ref="" key="Title" level="m"><div class="tagname-markup" data-norm="TITLE">title</div><div class="contents">Title</div></title></titleStmt>```

```/TEI/text[1]/body[1]/div[1]/p[1]/placeName[1]/div[2]/div[1]```
the location it almost refers to:
```<p><placeName ref="" key="Paris"><div class="tagname-markup" data-norm="PLACE">placeName</div><div class="contents">Paris</div></placeName> is a city in <placeName ref="" key="France"><div class="tagname-markup" data-norm="PLACE">placeName</div><div class="contents">France</div></placeName></p>```

In fact, each invalid xpath seems to refer to a div inside an entity, but erroneously appends an extra div to the xpath.

**Comment by ajmacdonald** [comment]
So, whoever is responsible for the server-side validation will need to have a look at this, I think.

**Comment by ilovan** [comment]
Thanks, @ajmacdonald , I believe the structure of the NERVE-generated tags will soon be changed to match what CWRC_Writer outputs, which should fix this issue. I will park it for now and come back to check it once the NERVE output is changed (those divs should not be in anyway)
