### ISSUE TITLE
Modify tag list so that the tag nicknames, when available, are shown alongside tag names

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#75]
E.g. the line for the `<ab>` tag should read `<ab> (anonymous block)`

**Comment by ajmacdonald** [comment]
@SusanBrown is this where you'd like to see the full names?
![taglist](https://user-images.githubusercontent.com/882444/38390900-ad730d46-38f0-11e8-869a-e5336b997eb4.png)

**Comment by SusanBrown** [comment]
Yes, and in the same list when it appears in the right-click menu within the text editor, and in the ones for tagging actions that appear on right clicks on tag names within the left hand Tag panel.

**Comment by ilovan** [comment]
confirmed

**Comment by ilovan** [comment]
work complete and deployed
