### ISSUE TITLE
Convert to entity - glitch

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#8]
This is a full scenario:

1. Select a name tag in either text area or structure panel
2. Click on "Convert to entity" in the right-click menu
           Step result: the entity lookup (currently just VIAF pops up)
3. Click outside the pop-up window, without selecting any hit in the dropdown (if any available)
           Step result: entity STILL gets created.

![screen shot 2017-11-01 at 3 33 42 pm](https://user-images.githubusercontent.com/6600070/32299690-1edf63e8-bf1c-11e7-821d-dbb9648bdd39.png)

4. Select a different name tag in either text area or structure panel
5.  Click on "Convert to entity" in the right-click menu
           Step result: the entity lookup (currently just VIAF pops up)
6. Select a hit in the dropdown (if any available)
           Step result: NEW entity gets created, but also the entity created at 1-3 above  receives the same label as the entity created at 4-6 (but no ref)

![screen shot 2017-11-01 at 3 34 39 pm](https://user-images.githubusercontent.com/6600070/32299913-e7951c42-bf1c-11e7-9fbf-583c2590077a.png)

7. Right-click on the entity created at 1-3 above - select "Edit entity" 
8. Select a hit in the dropdown (if any available) or change the text of the lookup and select one of the hits you receive
       Step result: Entity created at 1-3 is modified as expected (label changed and ref added), but the entity created at 4-6 also changes it's lablel

![screen shot 2017-11-01 at 4 01 02 pm](https://user-images.githubusercontent.com/6600070/32300181-ed4da874-bf1d-11e7-914e-37a69eb826c8.png)
 
@jchartrand , I am not sure who should this go to, you or Andrew?
Can you please assign?

**Comment by ajmacdonald** [comment]
@ilovan I'm trying to re-create this on dev-cwrc-writer but I can't. Can you confirm it still occurs?

**Comment by ilovan** [comment]
I can't for now, but I want to test it more thoroughly both on dev 05 and in the GitWriter.

**Comment by ilovan** [comment]
Nope, can't reproduce it anymore (though it was reproducible at the time; maybe it got fixed when you folks made other changes to the code/build process?

I will close it for now.
