### ISSUE TITLE
Logout option

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#83]
Gitwriter stores a token issued for access to GitWriter.
Create a logout option that destroys the token.

**Comment by ilovan** [comment]
Add an "Exit" button to the ribbon. 

Behaviour: 
1. User clicks on "Exit"
2. Popup: "You are about to exit CWRC-Writer. Any unsaved changes will be lost. Do you want to continue? Yes/Cancel
Yes - token destroyed - user returns to the landing page
Cancel - nothing happens (user can save and click exit again)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-git-dialogs/commit/0171db6a9f7f52e6a6714040567ccd090d661873

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/07afbfc43714acfcb575a3c228ece8649889f1eb
