### ISSUE TITLE
ref tag: only create hyperlink if target attribute has value beginning with "http"

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#87]
Not sure if this is a css issue or not.
The first example below from the TEI guidelines should generate a hyperlink but the second should not.
![image](https://user-images.githubusercontent.com/545952/38772629-aebf7bd8-4009-11e8-9e6c-2babd5808904.png)

**Comment by ajmacdonald** [comment]
@SusanBrown by hyperlink, do you mean the popup with a clickable link that appears when you mouseover a link entity? If you mean the blue colour, then yes that's in the TEI css.

**Comment by ajmacdonald** [comment]
3cd3519a95987012297d5a2f479af0a574313035

**Comment by SusanBrown** [comment]
Yes I mean this.  Ideally, we want this:
![image](https://user-images.githubusercontent.com/545952/45052436-c85bc900-b054-11e8-9431-5bc81188b763.png)
but not this:
![image](https://user-images.githubusercontent.com/545952/45052451-d6114e80-b054-11e8-8864-4d244a9b3b38.png)

@ilovan Do you know if there's any way to get the css to pass over the ref tag if the start of the value of the target attribute value doesn't match "http"?

**Comment by ilovan** [comment]
I believe it has to be Javascript, as I am not aware of any css selector that would allow us to do that.

**Comment by ajmacdonald** [comment]
@SusanBrown I haven't updated https://dev-cwrc-writer.cwrc.ca/ but the code is done. Just to confirm: should there be any pop-up at all for non-http targets? i.e. do you still want to see "#intertextuality" in a pop-up (but it can't be clicked to open a new window)?

**Comment by SusanBrown** [comment]
Fabulous.

No, I don’t think we want to see anything if the target doesn’t begin with http/https.

On Sep 4, 2018, at 4:07 PM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


@SusanBrown<https://github.com/SusanBrown> I haven't updated https://dev-cwrc-writer.cwrc.ca/ but the code is done. Just to confirm: should there be any pop-up at all for non-http targets? i.e. do you still want to see "#intertextuality" in a pop-up (but it can't be clicked to open a new window)?

**Comment by ajmacdonald** [comment]
aaebd961f64412c107127491d5dd4bbc28cf107c

**Comment by jchartrand** [comment]
I know Andrew has fixed it with js, but if ever CSS was needed, this CSS for `<a href="">` tags might work (adapting it to the appropriate tag and attribute):

```
a:not([href^='http'])
{
    visibility: hidden;
}
```

**Comment by ilovan** [comment]
confirmed fixed in CWRC-Writer
