### ISSUE TITLE
Save document popup help text - confusing

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#9]
When saving a document, the following form pops up:
![capture](https://user-images.githubusercontent.com/6600070/32801925-bc21fb9c-c93b-11e7-9d87-a7b9926e9a9c.PNG)

The Label states "Document Name" while the help text states "The name to give the new Github repository that will be created for the document. "

Confusion continues for the description field: both label and help text state "document", but the field actually produces the readme of the newly created repository.

**Comment by jchartrand** [comment]
Easily fixed - what wording would you like?

**Comment by ilovan** [comment]
I think we need three separate fields:

1. File name (label: "Save file as:"; help text: "Provide file name" )
2. Repo name (label: "New repository name"; help text: "Provide a name for the new GitHub repository")
3. Repo description (label: "New repository description"; help text: "Provide a description to fill in the readme file of the new repository")

Make 1 and 2 required fields and 3 optional.

**Comment by jchartrand** [comment]
Now I see the confusion.

The same filename (document.xml) is used for every CWRC repository (so the loader knows what filename in the repository to load).  I’ve called it document.xml, and it could be called something else, but to keep things simple it would have to be the same across repositories.  To allow different filenames across repositories would complicate things considerably, but if it is necessary we can do that.

Let me know what you’d like to do.
