### ISSUE TITLE
.cwrc selectors, can they be changed to .cwrc_wrapper?

### ISSUE THREAD

**Issue by bradklaver** [cwrc/CWRC-WriterBase#93]
https://github.com/cwrc/CWRC-WriterBase/blob/6522ccf3bd6c36f67dfe20246dd33c7b07d41e5f/src/css/style.css#L26
@ajmacdonald 
Can these be changed to be .cwrc_wrapper so they only apply wihtin the cwrc_writer portion of the page?  Its messing up the styles on the theme outside of it.

**Comment by ajmacdonald** [comment]
@bradklaver the cwrc class is used in a lot of the code so I'm hesitant to make that change. However I'm currently adding the cwrc class to the document body ( https://github.com/cwrc/CWRC-WriterBase/blob/master/src/js/writer.js#L776 ) and I think I've compartmentalized things enough that I can stop doing that. I hope that doing this should solve the problem.

**Comment by SusanBrown** [comment]
@bradklaver Does what Andrew has done work?
