### ISSUE TITLE
tagLabel (tag full name) showing up in the XML tags

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#94]
This happens:
1.  when you are creating the tags from scratch (select the string and click on tag)
2. when you take an existing tag (e.g. a paragraph) and click on change tag to transforming into something else (e.g. a heading)

Here is how it looks:

![image](https://user-images.githubusercontent.com/6600070/40077185-da7eeb84-584e-11e8-85c0-999aa9d821d5.png)

**Comment by bradklaver** [comment]
@ajmacdonald I've been asked to deploy this.  Does the islandora_cwrc_writer module need to have npm rebuild run, pulling this change into islandora_cwrc_writer, then I need to deploy that?  I don't think we use this library anymore directly on the site.  Correct me if I'm wrong, I'm not certain.
cc: @ilovan

**Comment by ajmacdonald** [comment]
@bradklaver yes it does. I'll put together the Islandora build and let you know when it's ready.

**Comment by ajmacdonald** [comment]
@bradklaver here's the latest: https://github.com/cwrc/Islandora-CWRC-Writer/commit/8ed2593a32eba3384437b56178cb7f92bc540c52

**Comment by ajmacdonald** [comment]
@bradklaver hold off if you haven't already deployed. I'm looking into fixing this as well https://github.com/cwrc/CWRC-WriterBase/issues/98

**Comment by bradklaver** [comment]
Alrighty - will leave this tab open till I leave today

**Comment by bradklaver** [comment]
I have not deployed

**Comment by ajmacdonald** [comment]
@bradklaver I think you can go ahead and deploy. The cwrc entity lookup in the current build will work when the https issue gets resolved server side.

**Comment by bradklaver** [comment]
I deployed shortly after Andrew posted his previous comment.

**Comment by ilovan** [comment]
confirmed completed

**Comment by ilovan** [comment]
work complete and deployed
