### ISSUE TITLE
Scrolling in tag/entity/relations panels doesn't work well without a mouse

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#95]
People working with touchpads (not touchscreens) are unable to scroll.

**Comment by ajmacdonald** [comment]
@SusanBrown is this in regards to the viewer mode or are people using touch devices to edit?

**Comment by SusanBrown** [comment]
Sorry I should have been more explicit. This is with regards to a touchpad pointer device, not a touchscreen.

**Comment by SusanBrown** [comment]
@ajmacdonald Is this clear now?

**Comment by SusanBrown** [comment]
Just retested and it seems fine so closing and hoping it was a glitch.
