### ISSUE TITLE
Full screen mode not working too well for viewing

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#96]
![image.png](https://images.zenhubusercontent.com/5a60ec3a4b5806bc2bc34e2e/b682551e-d39b-4c15-ae28-23e79735d59a)

**Comment by SusanBrown** [comment]
Also the edit mode: works lovely in most contexts (everyone in our workshop except for me, and previously on my iMac ).
MacBook Air ca. 2015
Browser Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Document: https://beta.cwrc.ca/islandora/object/cwrc%3A7718bbb4-1e8b-4091-8385-5bf53abf6625/edit-cwrc

[this is the embedded CWRC-Writer. @ilovan perhaps it should be moved?]

**Comment by ajmacdonald** [comment]
Note to self: this seems to be Mac specific issue

**Comment by SusanBrown** [comment]
Can't reproduce.
