### ISSUE TITLE
CWRC beta entity lookups: returns CWRC top page instead of preview and adds weird URIs to the document

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#98]
The preview popup in the entity lookup is showing the CWRC home page instead of the entity page for that entity. 

Also, the URI that gets added to the document is weird and redirects to the top level collection. 

E.g what **should** be added: http://commons.cwrc.ca/entityPID
what **is** added: https://beta.cwrc.ca/islandora/cwrc_entities/v1/islandora/object/cwrc:6a8543f1-0448-4657-a4ac-4614da983655

**Comment by ajmacdonald** [comment]
@jefferya @ilovan Since it wasn't working either way, I've updated dev-06 to use https://commons.cwrc.ca so that it will work when the certificate is updated

**Comment by jefferya** [comment]
Maybe fixed but I've no idea how to test @ilovan @ajmacdonald

**Comment by ajmacdonald** [comment]
@jefferya I tested it on beta.cwrc.ca and it works for me

**Comment by ilovan** [comment]
Confirmed it works.
